-- Aktualizacja ścieżek media (ULID → SEO)
START TRANSACTION;

UPDATE media SET file_path='media/reczniki-z-haftem-4-duze-w-koszu.png', name='reczniki-z-haftem-4-duze-w-koszu' WHERE id=1011 AND file_path='media/01KPBE74X0P5T5TF7AQSXEES9Z.png';
UPDATE media SET file_path='media/4-reczniki-kapielowe-w-koszu.png', name='4-reczniki-kapielowe-w-koszu' WHERE id=1006 AND file_path='media/01KP8M5EH9ZJMS721MM7D4CTG0.png';
UPDATE media SET file_path='media/reczniki-z-haftem-4duzeserce.png', name='reczniki-z-haftem-4duzeserce' WHERE id=1012 AND file_path='media/01KPBENQA4ATQ7Y4782XJ0NPE5.png';
UPDATE media SET file_path='media/4-reczniki-kapielowe-z-imionami.png', name='4-reczniki-kapielowe-z-imionami' WHERE id=1014 AND file_path='media/01KPDVAV0NCFXS6EEJW1J5XVNA.png';
UPDATE media SET file_path='media/4-reczniki-duze-zona-i-maz.png', name='4-reczniki-duze-zona-i-maz' WHERE id=1015 AND file_path='media/01KPDVQHSKX8WXG8JQ9W820EPF.png';
UPDATE media SET file_path='media/reczniki-z-haftem-4-duze-bialy-szary.png', name='reczniki-z-haftem-4-duze-bialy-szary' WHERE id=1016 AND file_path='media/01KPDZEZ2MG7SDBMXJR618QCGD.png';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-rodzinny-komplet-prezentowy.png', name='reczniki-z-haftem-rodzinny-komplet-prezentowy' WHERE id=906 AND file_path='media/realizations/01KNE62VHDEY14ADXSESW73WE8.png';
UPDATE media SET file_path='media/reczniki-z-haftem-2duze-2-srednie-opakowanie.png', name='reczniki-z-haftem-2duze-2-srednie-opakowanie' WHERE id=936 AND file_path='media/01KNRS5K687P6Y42Z71TW661BP.png';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-rodzinny-komplet-prezentowy-1.png', name='reczniki-z-haftem-rodzinny-komplet-prezentowy-1' WHERE id=919 AND file_path='media/realizations/i7qbofi7qbofi7qb.png';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-rodzinny-komplet-prezentowy-2.png', name='reczniki-z-haftem-rodzinny-komplet-prezentowy-2' WHERE id=904 AND file_path='media/realizations/01KNE62VHA4EVDEQFQX6WFMFNJ.png';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-rodzinny-komplet-prezentowy.jpg', name='reczniki-z-haftem-rodzinny-komplet-prezentowy' WHERE id=112 AND file_path='media/realizations/5164ff0b62492_reczniki_z_haftem.jpg';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-rodzinny-komplet-prezentowy-3.png', name='reczniki-z-haftem-rodzinny-komplet-prezentowy-3' WHERE id=1002 AND file_path='media/uploads/01KP8BZ85WDETAZYJPHP3ZNVXV.png';
UPDATE media SET file_path='media/reczniki-z-haftem-4-w-koszu.png', name='reczniki-z-haftem-4-w-koszu' WHERE id=1007 AND file_path='media/01KPBCYVZQRBDZX1M26DDXXK9H.png';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-prezent-dla-pary.png', name='reczniki-z-haftem-prezent-dla-pary' WHERE id=917 AND file_path='media/realizations/618lyh618lyh618l.png';
UPDATE media SET file_path='media/reczniki-z-haftem-2-duze-w-koszu.png', name='reczniki-z-haftem-2-duze-w-koszu' WHERE id=938 AND file_path='media/01KNRXXE9MW9QEF2M1YN1F0S6N.png';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice.png', name='reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice' WHERE id=918 AND file_path='media/realizations/p02hbyp02hbyp02h.png';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-1.png', name='reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-1' WHERE id=916 AND file_path='media/realizations/qe4s9dqe4s9dqe4s.png';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-2.png', name='reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-2' WHERE id=1001 AND file_path='media/uploads/01KP8BZ85SW4QQZ1Y21DJ2H9NH.png';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-3.png', name='reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-3' WHERE id=994 AND file_path='media/uploads/01KP8BZ85AXB4NDCM4BQ4FFJ7Z.png';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-prezent-dla-dwojga.png', name='reczniki-z-haftem-prezent-dla-dwojga' WHERE id=991 AND file_path='media/uploads/01KP8BZ8542X4W37NR33QVTNEJ.png';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-4.png', name='reczniki-z-haftem-ekskluzywny-prezent-na-slub-lub-rocznice-4' WHERE id=988 AND file_path='media/uploads/01KP8BZ84XJ6ECB7G5GJ0RWMWW.png';
UPDATE media SET file_path='media/2-reczniki-z-sercem-i-golebiami.png', name='2-reczniki-z-sercem-i-golebiami' WHERE id=1013 AND file_path='media/01KPBF3XE5EG6B8DTDK29N062P.png';
UPDATE media SET file_path='media/reczniki-z-haftem-duzy-sredni-opakowanie.png', name='reczniki-z-haftem-duzy-sredni-opakowanie' WHERE id=937 AND file_path='media/01KNRZNEFT5E5XJJBTY477X087.png';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-prezent-dla-dwojga-1.png', name='reczniki-z-haftem-prezent-dla-dwojga-1' WHERE id=986 AND file_path='media/uploads/01KP8BZ84SF28PD2VVTY2M8XXM.png';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-prezent-dla-dwojga-2.png', name='reczniki-z-haftem-prezent-dla-dwojga-2' WHERE id=987 AND file_path='media/uploads/01KP8BZ84V61TKVFR055678S5D.png';
UPDATE media SET file_path='media/uploads/reczniki-z-haftem-prezent-dla-dwojga-3.png', name='reczniki-z-haftem-prezent-dla-dwojga-3' WHERE id=989 AND file_path='media/uploads/01KP8BZ850NG81285FT1NEZYJR.png';
UPDATE media SET file_path='media/reczniki-z-haftem-serce.png', name='reczniki-z-haftem-serce' WHERE id=1009 AND file_path='media/01KPBD3207168945YB56FGF6D6.png';
UPDATE media SET file_path='media/reczniki-z-haftem-slonce.png', name='reczniki-z-haftem-slonce' WHERE id=1010 AND file_path='media/01KPBD41HX9W60P14YQRRPSDZN.png';
UPDATE media SET file_path='media/reczniki-z-haftem-autko.png', name='reczniki-z-haftem-autko' WHERE id=1008 AND file_path='media/01KPBD1TQCP90NDY3KN5XDA4RW.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent.png', name='recznik-kapielowy-z-haftem-na-prezent' WHERE id=1004 AND file_path='media/uploads/01KP8BZ86009TBMQQYS4ZM0MJH.png';
UPDATE media SET file_path='media/reczniki-z-haftem-duzy-w-koszu.png', name='reczniki-z-haftem-duzy-w-koszu' WHERE id=942 AND file_path='media/01KNS09RCG1R0S0NEQ531HJDSB.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-1.png', name='recznik-kapielowy-z-haftem-na-prezent-1' WHERE id=1000 AND file_path='media/uploads/01KP8BZ85QQEKABSDK0WB8RPWP.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-2.png', name='recznik-kapielowy-z-haftem-na-prezent-2' WHERE id=999 AND file_path='media/uploads/01KP8BZ85M58W8JM28TAG5JZPF.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-3.png', name='recznik-kapielowy-z-haftem-na-prezent-3' WHERE id=997 AND file_path='media/uploads/01KP8BZ85GBBX3Y7XHZ9ERBCMR.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-4.png', name='recznik-kapielowy-z-haftem-na-prezent-4' WHERE id=996 AND file_path='media/uploads/01KP8BZ85E00FYBAP0B1EQP1N5.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-5.png', name='recznik-kapielowy-z-haftem-na-prezent-5' WHERE id=995 AND file_path='media/uploads/01KP8BZ85C20WF7MY9ER8VDFGT.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-6.png', name='recznik-kapielowy-z-haftem-na-prezent-6' WHERE id=990 AND file_path='media/uploads/01KP8BZ852JM878R4ZTGQJP6RW.png';
UPDATE media SET file_path='media/reczniki-z-haftem-duzy.png', name='reczniki-z-haftem-duzy' WHERE id=941 AND file_path='media/01KNRZBDQ2XFK5G6WYV6Y2CY4P.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-7.png', name='recznik-kapielowy-z-haftem-na-prezent-7' WHERE id=993 AND file_path='media/uploads/01KP8BZ858P9NZJ3GC4GSR421N.png';
UPDATE media SET file_path='media/uploads/recznik-kapielowy-z-haftem-na-prezent-8.png', name='recznik-kapielowy-z-haftem-na-prezent-8' WHERE id=992 AND file_path='media/uploads/01KP8BZ8564Y2RCN5R581ZYRSA.png';
UPDATE media SET file_path='media/reczniki-z-haftem-2-male-w-koszu.png', name='reczniki-z-haftem-2-male-w-koszu' WHERE id=939 AND file_path='media/01KNRXXVPWGTRJSJMKGQJQD3A0.png';
UPDATE media SET file_path='media/uploads/recznik-z-haftem-na-prezent.png', name='recznik-z-haftem-na-prezent' WHERE id=1003 AND file_path='media/uploads/01KP8BZ85YZVV4FJ6VD6AS5WCA.png';
UPDATE media SET file_path='media/reczniki-z-haftem-maly.png', name='reczniki-z-haftem-maly' WHERE id=940 AND file_path='media/01KNRZB39KYQ3E259QGTMMGH46.png';
UPDATE media SET file_path='media/uploads/recznik-z-haftem-na-prezent-1.png', name='recznik-z-haftem-na-prezent-1' WHERE id=998 AND file_path='media/uploads/01KP8BZ85JSKD1JX699S14ZS52.png';
UPDATE media SET file_path='media/uploads/recznik-z-haftem-na-prezent-2.png', name='recznik-z-haftem-na-prezent-2' WHERE id=985 AND file_path='media/uploads/01KP8BZ84QTD9DT55CNPJBF5CX.png';
UPDATE media SET file_path='media/realizations/zestaw-4-recznikow-kapielowych-z-imionami-i-czapka-mikolaja-1.jpg', name='zestaw-4-recznikow-kapielowych-z-imionami-i-czapka-mikolaja-1' WHERE id=15 AND file_path='media/realizations/546f2a3d28dfc_4-reczniki-prezent-na-mikol.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-srednie-w-koszu-z-imionami-i-czapka-mikolaja-1.jpg', name='2-reczniki-srednie-w-koszu-z-imionami-i-czapka-mikolaja-1' WHERE id=16 AND file_path='media/realizations/546f2a3524289_2-reczniki-prezent-na-mikol.jpg';
UPDATE media SET file_path='media/realizations/1-recznik-kapielowy-z-imieniem-i-czapka-mikolaja-1.jpg', name='1-recznik-kapielowy-z-imieniem-i-czapka-mikolaja-1' WHERE id=17 AND file_path='media/realizations/528125124226e_mikolaj.jpg';
UPDATE media SET file_path='media/realizations/duzy-recznik-z-wyhaftowanym-imieniem-i-czapka-mikolaja-prezent-na-mikolajki-z-im-1.jpg', name='duzy-recznik-z-wyhaftowanym-imieniem-i-czapka-mikolaja-prezent-na-mikolajki-z-im-1' WHERE id=18 AND file_path='media/realizations/50965c657f425_czapka-mkolaja.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-kapielowe-z-haftem-imion-i-czapek-mikolaja-1.jpg', name='2-reczniki-kapielowe-z-haftem-imion-i-czapek-mikolaja-1' WHERE id=19 AND file_path='media/realizations/5282fbeb2cdd7_mikolajki.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-3.jpg', name='2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-3' WHERE id=70 AND file_path='media/realizations/500e9ad20b037_reczniki-bezowe.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-4.jpg', name='2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-4' WHERE id=71 AND file_path='media/realizations/500fb0dd40e84_bezowo-bordowy.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-5.jpg', name='2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-5' WHERE id=72 AND file_path='media/realizations/5012a55862e0a_fioletowy-recznik-na-prteze.jpg';
UPDATE media SET file_path='media/realizations/4-reczniki-kapielowe-z-haftem-slubnym-w-kuferku-bambusowym-1.jpg', name='4-reczniki-kapielowe-z-haftem-slubnym-w-kuferku-bambusowym-1' WHERE id=77 AND file_path='media/realizations/5022769e4d7fe_reczniki_haftowane_w_kuferk.jpg';
UPDATE media SET file_path='media/realizations/biale-i-brazowe-reczniki-kapielowe-z-wyhaftowanym-imieniem-i-motywem-serc-calosc-1.jpg', name='biale-i-brazowe-reczniki-kapielowe-z-wyhaftowanym-imieniem-i-motywem-serc-calosc-1' WHERE id=78 AND file_path='media/realizations/502671553e937_kosz_reczniki_haftowane_na_.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-kapielowe-z-imionami-i-wzorem-oczu-1.png', name='2-reczniki-kapielowe-z-imionami-i-wzorem-oczu-1' WHERE id=79 AND file_path='media/realizations/502d38d0cfa68_magda.png';
UPDATE media SET file_path='media/realizations/4-reczniki-w-koszu-1.jpg', name='4-reczniki-w-koszu-1' WHERE id=88 AND file_path='media/realizations/50501de14a904_imionami.jpg';
UPDATE media SET file_path='media/realizations/komplet-bezowych-i-turkusowych-4-recznikow-1.jpg', name='komplet-bezowych-i-turkusowych-4-recznikow-1' WHERE id=91 AND file_path='media/realizations/50617993cca58_kuf.jpg';
UPDATE media SET file_path='media/realizations/reczniki-z-haftem-maz-i-zona-1.jpg', name='reczniki-z-haftem-maz-i-zona-1' WHERE id=95 AND file_path='media/realizations/508a34510c821_mazzona.jpg';
UPDATE media SET file_path='media/realizations/2-duze-kremowe-reczniki-z-wyhaftowanymi-imionami-i-roza-1.jpg', name='2-duze-kremowe-reczniki-z-wyhaftowanymi-imionami-i-roza-1' WHERE id=97 AND file_path='media/realizations/509f88dd7a5cd_ROZE.jpg';
UPDATE media SET file_path='media/realizations/duzy-recznik-kapielowy-z-haftem-litery-1.jpg', name='duzy-recznik-kapielowy-z-haftem-litery-1' WHERE id=109 AND file_path='media/realizations/514f18310c428_P3.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-kapielowe-z-wyhaftowanym-monogramem-1.jpg', name='2-reczniki-kapielowe-z-wyhaftowanym-monogramem-1' WHERE id=115 AND file_path='media/realizations/5199ef8690888_monogram.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-kapielowe-z-imionami-i-slowikami-na-rocznice-slubu-1.jpg', name='2-reczniki-kapielowe-z-imionami-i-slowikami-na-rocznice-slubu-1' WHERE id=116 AND file_path='media/realizations/519e08104344e_reczniki-z-imionami.jpg';
UPDATE media SET file_path='media/realizations/2-biale-reczniki-kapielowe-z-czarnym-haftem-maz-i-zona-1.jpg', name='2-biale-reczniki-kapielowe-z-czarnym-haftem-maz-i-zona-1' WHERE id=118 AND file_path='media/realizations/51a35202ed4d3_recznik-maz-zona.jpg';
UPDATE media SET file_path='media/realizations/1-recznik-sredni-z-haftem-z-okazji-dnia-taty-1.jpg', name='1-recznik-sredni-z-haftem-z-okazji-dnia-taty-1' WHERE id=121 AND file_path='media/realizations/51b81f302e140_st1.jpg';
UPDATE media SET file_path='media/realizations/1-duzy-recznik-z-haftem-super-tata-1.jpg', name='1-duzy-recznik-z-haftem-super-tata-1' WHERE id=122 AND file_path='media/realizations/51b81f284c71f_st.jpg';
UPDATE media SET file_path='media/realizations/2-reczniki-z-haftem-1.jpg', name='2-reczniki-z-haftem-1' WHERE id=125 AND file_path='media/realizations/51d658fa942cc_haft-wisienki.jpg';
UPDATE media SET file_path='media/realizations/4-reczniki-z-z-haftem-zestaw-bezowo-brazowy-1.jpg', name='4-reczniki-z-z-haftem-zestaw-bezowo-brazowy-1' WHERE id=126 AND file_path='media/realizations/52203f1856818_szlafroki1.jpg';
UPDATE media SET file_path='media/realizations/zestaw-2-recznikow-duzych-i-2-srednich-z-haftem-maz-i-zona-1.jpg', name='zestaw-2-recznikow-duzych-i-2-srednich-z-haftem-maz-i-zona-1' WHERE id=128 AND file_path='media/realizations/522585ef257f2_kosz.jpg';
UPDATE media SET file_path='media/realizations/zestaw-czarno-rozowy-1-recznik-sredni-i-1-recznik-kapielowy-z-haftem-swinki-i-im-1.jpg', name='zestaw-czarno-rozowy-1-recznik-sredni-i-1-recznik-kapielowy-z-haftem-swinki-i-im-1' WHERE id=453 AND file_path='media/realizations/550fe2ad9bb4c_roz.jpg';
UPDATE media SET file_path='media/4-reczniki-w-koszu.png', name='4-reczniki-w-koszu' WHERE id=1017 AND file_path='media/01KQDCYD2S01A4G4NR6J2T8TRY.png';
UPDATE media SET file_path='media/reczniki-z-haftem-4-biale-na-slub.png', name='reczniki-z-haftem-4-biale-na-slub' WHERE id=1018 AND file_path='media/01KQVN63DRCSA3YYNP2DQ9VR23.png';
UPDATE media SET file_path='media/reczniki-z-haftem-mama.png', name='reczniki-z-haftem-mama' WHERE id=1022 AND file_path='media/01KR9SPX232D561D7YYWDZMWX0.png';
UPDATE media SET file_path='media/reczniki-z-haftem-4-kremgranat.png', name='reczniki-z-haftem-4-kremgranat' WHERE id=1023 AND file_path='media/01KRF246SVDC773G7NRD4NJ1BT.png';
UPDATE media SET file_path='media/reczniki-z-haftem-1roz.png', name='reczniki-z-haftem-1roz' WHERE id=1024 AND file_path='media/01KRF2AA68N8JKVB1RAVZFDRCD.png';
UPDATE media SET file_path='media/reczniki-z-haftem-4kremy.png', name='reczniki-z-haftem-4kremy' WHERE id=1025 AND file_path='media/01KRF2GP6DR688EWTJSK06MVGX.png';

-- Aktualizacja ścieżek realizacji
UPDATE realizations SET file_path='realizations/zestaw-4-recznikow-kapielowych-z-imionami-i-czapka-mikolaja.jpg' WHERE id=1 AND file_path='realizations/546f2a3d28dfc_4-reczniki-prezent-na-mikol.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-srednie-w-koszu-z-imionami-i-czapka-mikolaja.jpg' WHERE id=2 AND file_path='realizations/546f2a3524289_2-reczniki-prezent-na-mikol.jpg';
UPDATE realizations SET file_path='realizations/1-recznik-kapielowy-z-imieniem-i-czapka-mikolaja.jpg' WHERE id=3 AND file_path='realizations/528125124226e_mikolaj.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-imionami-i-czapka-mikolaja.jpg' WHERE id=4 AND file_path='realizations/50965c657f425_czapka-mkolaja.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-haftem-imion-i-czapek-mikolaja.jpg' WHERE id=5 AND file_path='realizations/5282fbeb2cdd7_mikolajki.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu.jpg' WHERE id=56 AND file_path='realizations/500e9ad20b037_reczniki-bezowe.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-1.jpg' WHERE id=57 AND file_path='realizations/500fb0dd40e84_bezowo-bordowy.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-okazji-slubu-z-imionami-i-data-slubu-2.jpg' WHERE id=58 AND file_path='realizations/5012a55862e0a_fioletowy-recznik-na-prteze.jpg';
UPDATE realizations SET file_path='realizations/4-reczniki-kapielowe-z-haftem-slubnym-w-kuferku-bambusowym.jpg' WHERE id=63 AND file_path='realizations/5022769e4d7fe_reczniki_haftowane_w_kuferk.jpg';
UPDATE realizations SET file_path='realizations/biale-i-brazowe-reczniki-kapielowe-z-wyhaftowanym-imieniem-i-motywem-serc-calosc.jpg' WHERE id=64 AND file_path='realizations/502671553e937_kosz_reczniki_haftowane_na_.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-imionami-i-wzorem-oczu.png' WHERE id=65 AND file_path='realizations/502d38d0cfa68_magda.png';
UPDATE realizations SET file_path='realizations/4-reczniki-w-koszu.jpg' WHERE id=74 AND file_path='realizations/50501de14a904_imionami.jpg';
UPDATE realizations SET file_path='realizations/komplet-bezowych-i-turkusowych-4-recznikow.jpg' WHERE id=77 AND file_path='realizations/50617993cca58_kuf.jpg';
UPDATE realizations SET file_path='realizations/reczniki-z-haftem-maz-i-zona.jpg' WHERE id=81 AND file_path='realizations/508a34510c821_mazzona.jpg';
UPDATE realizations SET file_path='realizations/duzy-recznik-z-wyhaftowanym-imieniem-i-czapka-mikolaja-prezent-na-mikolajki-z-im.jpg' WHERE id=82 AND file_path='realizations/50965c657f425_czapka-mkolaja.jpg';
UPDATE realizations SET file_path='realizations/2-duze-kremowe-reczniki-z-wyhaftowanymi-imionami-i-roza.jpg' WHERE id=84 AND file_path='realizations/509f88dd7a5cd_ROZE.jpg';
UPDATE realizations SET file_path='realizations/duzy-recznik-kapielowy-z-haftem-litery.jpg' WHERE id=96 AND file_path='realizations/514f18310c428_P3.jpg';
UPDATE realizations SET file_path='realizations/zestaw-4-recznikow-z-haftem-maz-zona-w-koszu-wiklinowym.jpg' WHERE id=99 AND file_path='realizations/5164ff0b62492_reczniki_z_haftem.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-wyhaftowanym-monogramem.jpg' WHERE id=102 AND file_path='realizations/5199ef8690888_monogram.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-kapielowe-z-imionami-i-slowikami-na-rocznice-slubu.jpg' WHERE id=103 AND file_path='realizations/519e08104344e_reczniki-z-imionami.jpg';
UPDATE realizations SET file_path='realizations/2-biale-reczniki-kapielowe-z-czarnym-haftem-maz-i-zona.jpg' WHERE id=105 AND file_path='realizations/51a35202ed4d3_recznik-maz-zona.jpg';
UPDATE realizations SET file_path='realizations/1-recznik-sredni-z-haftem-z-okazji-dnia-taty.jpg' WHERE id=108 AND file_path='realizations/51b81f302e140_st1.jpg';
UPDATE realizations SET file_path='realizations/1-duzy-recznik-z-haftem-super-tata.jpg' WHERE id=109 AND file_path='realizations/51b81f284c71f_st.jpg';
UPDATE realizations SET file_path='realizations/2-reczniki-z-haftem.jpg' WHERE id=112 AND file_path='realizations/51d658fa942cc_haft-wisienki.jpg';
UPDATE realizations SET file_path='realizations/4-reczniki-z-z-haftem-zestaw-bezowo-brazowy.jpg' WHERE id=113 AND file_path='realizations/52203f1856818_szlafroki1.jpg';
UPDATE realizations SET file_path='realizations/zestaw-2-recznikow-duzych-i-2-srednich-z-haftem-maz-i-zona.jpg' WHERE id=115 AND file_path='realizations/522585ef257f2_kosz.jpg';
UPDATE realizations SET file_path='realizations/zestaw-czarno-rozowy-1-recznik-sredni-i-1-recznik-kapielowy-z-haftem-swinki-i-im.jpg' WHERE id=127 AND file_path='realizations/550fe2ee80945_roz.jpg';
UPDATE realizations SET file_path='realizations/komplet-4-blekitnych-duzych-recznikow-z-haftem-w-koszu-prezent-dla-calej-rodziny.jpg' WHERE id=134 AND file_path='realizations/559039fb221c4blekitne.jpg';
UPDATE realizations SET file_path='realizations/reczniki-z-haftem-na-rocznice-slubu.png' WHERE id=172 AND file_path='realizations/01KNE62VHCFVQTXN5T5T04WYEP.png';
UPDATE realizations SET file_path='realizations/reczniki-z-haftem-na-rocznice-slubu-1.png' WHERE id=173 AND file_path='realizations/01KNE62VHEP3JSPJXBA6AQZGMH.png';
UPDATE realizations SET file_path='realizations/reczniki-z-haftem-na-rocznice-slubu-2.png' WHERE id=174 AND file_path='realizations/01KNE62VHH055BQCRWRS6QQC13.png';
UPDATE realizations SET file_path='realizations/reczniki-z-haftem-na-rocznice-slubu-3.png' WHERE id=175 AND file_path='realizations/01KNE62VHJEEM9AV9651TZ0E2T.png';

COMMIT;
